// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgVv9jHvJ4tt_2ZVLD_RJ88qlUwZnNtk',
    appId: '1:834676273805:web:f3a960e756071c6985a8c4',
    messagingSenderId: '834676273805',
    projectId: 'flutter-projects-27cb8',
    authDomain: 'flutter-projects-27cb8.firebaseapp.com',
    storageBucket: 'flutter-projects-27cb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25vzkFEiniZudZ-FcMp5YmQ7FJip6zEo',
    appId: '1:834676273805:android:3f33e4760b8fbf0985a8c4',
    messagingSenderId: '834676273805',
    projectId: 'flutter-projects-27cb8',
    storageBucket: 'flutter-projects-27cb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZI1PZz4nFKIeHfAX9gOcTqcIRg2i3gI',
    appId: '1:834676273805:ios:ce0e8ec9a370c7e485a8c4',
    messagingSenderId: '834676273805',
    projectId: 'flutter-projects-27cb8',
    storageBucket: 'flutter-projects-27cb8.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZI1PZz4nFKIeHfAX9gOcTqcIRg2i3gI',
    appId: '1:834676273805:ios:ce0e8ec9a370c7e485a8c4',
    messagingSenderId: '834676273805',
    projectId: 'flutter-projects-27cb8',
    storageBucket: 'flutter-projects-27cb8.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdgVv9jHvJ4tt_2ZVLD_RJ88qlUwZnNtk',
    appId: '1:834676273805:web:fed20978e2bf9c1585a8c4',
    messagingSenderId: '834676273805',
    projectId: 'flutter-projects-27cb8',
    authDomain: 'flutter-projects-27cb8.firebaseapp.com',
    storageBucket: 'flutter-projects-27cb8.appspot.com',
  );

}